// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

Texture2D<float4> _TilemapTexture;
Texture2D<float4> _SceneTexture;
RWTexture2D<float4> _OutputTexture;

int _Width;
int _Height;

float _sinInputInRadians;
float _waveStride;
float _waveHeight;
float _textureWorldX;
float _pixelsPerUnit;

[numthreads(8, 8, 1)]
void CSMain (uint3 id : SV_DispatchThreadID) {
    if (id.x >= (uint)_Width || id.y >= (uint)_Height) return;

    const int maxDist = 150;
    bool isWater = _SceneTexture[id.xy].a < 0.25;
    
    // if (!isWater) {
    //     _OutputTexture[id.xy] = float4(0, 0, 0, 0);
    //     return;
    // }
    
    float worldX = (_textureWorldX + id.x) / _pixelsPerUnit;
    uint offset = abs(sin((worldX + _sinInputInRadians) * _waveStride) * _waveHeight);
    
    int intersectionLen = 6;
    for (int i = 0; i <= offset + intersectionLen; i++) {
        int searchY = id.y - i;
        if (searchY <= 0) break;
        
        float alpha = _TilemapTexture[int2(id.x, searchY)].a;
        float belowAlpha = _TilemapTexture[int2(id.x, searchY - 1)].a;
        bool isEdge = alpha > 0.25 && belowAlpha < 0.95;
        
        int lowerRange = offset;
        int upperRange = offset + intersectionLen;
        int dist = id.y - searchY;
        bool isInRange = dist >= lowerRange && dist <= upperRange;
        
        if (isEdge && isInRange) {
            _OutputTexture[id.xy] = float4(0, 0, 0, 1);
            return;
        }
        
        // Make the water go to the intersection line
        if (isEdge) {
            _OutputTexture[id.xy] = float4(1, 1, 1, 1);
            return;
        }
    }

    // Walk upward from this pixel to find the nearest edge within range
    // for (int i = 0; i < maxDist; i++) {
    //     int searchY = id.y + i;
    //     if (searchY >= _Height - 1) break;
    //
    //     float alpha = _TilemapTexture[int2(id.x, searchY)].a;
    //     float aboveAlpha = _TilemapTexture[int2(id.x, searchY + 1)].a;
    //     bool isEdge = alpha < 0.25 && aboveAlpha > 0.95;
    //     
    //     if (i <= 5 && isEdge) {
    //         _OutputTexture[id.xy] = float4(0, 0, 0, 1);
    //         return;     
    //     }
    //     
    //     if (!isEdge) continue;
    //     
    //     int reflectY = clamp(searchY + (i + 1), 0, _Height - 1);
    //     float4 reflectColor = _SceneTexture[int2(id.x, reflectY)];
    //     
    //     // Its possible that the reflection pixel overshoots the land and samples the "void"
    //     if (reflectColor.a > 0.25) {
    //         float distComp = (i + 1) / (float)maxDist; 
    //         float fadeComp = smoothstep(0.0, 0.6, distComp);
    //         // _OutputTexture[id.xy] = lerp(reflectColor, float4(1, 1, 1, 1), fadeComp);
    //         _OutputTexture[id.xy] = float4(1, 1, 1, 1);
    //         return;
    //     }
    //     
    //     break;
    // }
    
    // If not reflecting but this pixel is water
    if (isWater) {
        _OutputTexture[id.xy] = float4(1, 1, 1, 1);
        return;
    }
    
    _OutputTexture[id.xy] = float4(0, 0, 0, 0);
}