// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

Texture2D<float4> _TilemapTexture;
Texture2D<float4> _SceneTexture;
RWTexture2D<float4> _OutputTexture;

int _width;
int _height;
int _waterLineLengthInPixels;
int _reflectionLengthInPixels;

float _sinOffsetInRadians;
float _waveStride;
float _waveHeightInPixels;
float _camWorldXInPixels;
float _pixelsPerUnit;
float _startReflectionFade;
float _endReflectionFade;

[numthreads(8, 8, 1)]
void CSMain (uint3 id : SV_DispatchThreadID) {
    uint maxX = _width - 1;
    uint maxY = _height - 1;
    
    if (id.x >= maxX || id.y >= maxY) return;

    if (_waterLineLengthInPixels > 0) {
        float fragWorldSpace = (_camWorldXInPixels + id.x) / _pixelsPerUnit;
        uint offset = abs(sin((fragWorldSpace + _sinOffsetInRadians) * _waveStride) * _waveHeightInPixels);
        
        for (int i = 0; i <= offset + _waterLineLengthInPixels; i++) {
            int searchY = id.y - i;
            if (searchY <= 0) break;
            
            float alpha = _TilemapTexture[int2(id.x, searchY)].a;
            float belowAlpha = _TilemapTexture[int2(id.x, searchY - 1)].a;
            bool isEdge = alpha > 0.25 && belowAlpha < 0.95;
            
            int lowerRange = offset;
            int upperRange = offset + _waterLineLengthInPixels;
            int dist = id.y - searchY;
            bool isInRange = dist >= lowerRange && dist <= upperRange;
            
            if (isEdge && isInRange) {
                _OutputTexture[id.xy] = float4(0, 0, 0, 1);
                return;
            }
            
            // Make the water go to the intersection line
            if (isEdge) {
                if (_reflectionLengthInPixels <= 0) {
                    _OutputTexture[id.xy] = float4(1, 1, 1, 1);
                    return;
                }
                
                int reflectY = clamp(id.y + (i + 1), 0, maxY);
                float4 reflectColor = _SceneTexture[int2(id.x, reflectY)];
                if (reflectColor.a > 0.25) {
                    float distComp = (i + 1) / (float)_reflectionLengthInPixels; 
                    float fadeComp = lerp(_startReflectionFade, _endReflectionFade, distComp);
                    _OutputTexture[id.xy] = lerp(reflectColor, float4(1, 1, 1, 1), fadeComp);
                    return;
                }
                
                break;
            }
        }
    }
    
    bool isWater = _SceneTexture[id.xy].a < 0.25;
    if (!isWater) {
        _OutputTexture[id.xy] = float4(0, 0, 0, 0);
        return;
    }

    if (_reflectionLengthInPixels > 0) {
        for (int i = 0; i < _reflectionLengthInPixels; i++) {
            int searchY = id.y + i;
            if (searchY >= maxY) break;
    
            float alpha = _TilemapTexture[int2(id.x, searchY)].a;
            float aboveAlpha = _TilemapTexture[int2(id.x, searchY + 1)].a;
            bool isEdge = alpha < 0.25 && aboveAlpha > 0.95;
        
            if (!isEdge) continue;
        
            int reflectY = clamp(searchY + (i + 1), 0, maxY);
            float4 reflectColor = _SceneTexture[int2(id.x, reflectY)];
        
            // Its possible that the reflection pixel overshoots the land and samples the "void"
            if (reflectColor.a > 0.25) {
                float distComp = (i + 1) / (float)_reflectionLengthInPixels; 
                float fadeComp = lerp(_startReflectionFade, _endReflectionFade, distComp);
                _OutputTexture[id.xy] = lerp(reflectColor, float4(1, 1, 1, 1), fadeComp);
                return;
            }
            
            break;
        }
    }
    
    // If didn't write to pixel but it is water
    if (isWater) {
        _OutputTexture[id.xy] = float4(1, 1, 1, 1);
        return;
    }
    
    _OutputTexture[id.xy] = float4(0, 0, 0, 0);
}